#!/bash/bin

if [ ${id} -ne 0 ] 
then
echo
echo " You need root Access"
sleep 10
exit 1
fi

## check number of processors

if [ `nproc` -eq 1 ] 
then
echo " This server is very small"
exit 99
fi

free -m
