#!/bash/bin

if  [ "${id}" != 0 ] 
then
echo
echo " You need root Access"
sleep 10

fi

## check number of processors
C=nproc

if [ "${C}" != 3 ] 
then
echo " This server is very big"

fi

free -m
exit 0
