#!/bash/bin

if [ ${id} -ne 0 ] 
then
echo
echo " You need root Access"
sleep 10
exit 0
fi

## check number of processors
C = nproc

if [ ${C} -eq 1 ] 
then
echo " This server is very small"
exit 2
fi

free -m
exit 0
